#lang racket/base

;; version-info.rkt - Auto-generated version information
;; This file is regenerated by `make binary` or `make dist` from git tags.
;; Do not edit manually - changes will be overwritten during build.

(provide AR-CRAWL-VERSION)

;; Version from git tag (updated at build time)
(define AR-CRAWL-VERSION "v1.0.30")
