when:
  - event: [push, manual]
    branch: main
    path:
      include: ['src/**', 'Dockerfile', 'Makefile']
      on_empty: true

steps:
  - name: build-docker-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: anunaresearch/ar-crawl
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest,${CI_COMMIT_SHA}
      dockerfile: Dockerfile
      buildx_args:
        - --cache-from=type=registry,ref=anunaresearch/ar-crawl:cache
        - --cache-to=type=registry,ref=anunaresearch/ar-crawl:cache,mode=max
      platforms: linux/amd64
